# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diff.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Derivative")
        Form.resize(800, 500)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 90, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 230, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(110, 390, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(570, 70, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.fxxoutput = QtWidgets.QTextEdit(Form)
        self.fxxoutput.setGeometry(QtCore.QRect(230, 220, 251, 71))
        self.fxxoutput.setObjectName("fxxoutput")
        self.fxxxoutput = QtWidgets.QTextEdit(Form)
        self.fxxxoutput.setGeometry(QtCore.QRect(230, 370, 251, 71))
        self.fxxxoutput.setObjectName("fxxxoutput")
        self.fxinput = QtWidgets.QLineEdit(Form)
        self.fxinput.setGeometry(QtCore.QRect(230, 80, 251, 71))
        self.fxinput.setObjectName("fxinput")
        self.pushButton.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.fxxoutput.raise_()
        self.fxxxoutput.raise_()
        self.fxinput.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Derivative"))
        self.label.setText(_translate("Form", "f(x) ="))
        self.label_2.setText(_translate("Form", "f\'(x) ="))
        self.label_3.setText(_translate("Form", "f\'\'(x) ="))
        self.pushButton.setText(_translate("Form", "Вычислить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
